object GradleModule {

    const val ROOT_PROJECT_NAME = "sdk-library-java"

    const val BOM = ":$ROOT_PROJECT_NAME-bom"

    const val CACHE_ALL = ":$ROOT_PROJECT_NAME-cache-all"
    const val CACHE_CAFFEINE = ":$ROOT_PROJECT_NAME-cache-caffeine"
    const val CACHE_CONTRACT = ":$ROOT_PROJECT_NAME-cache-contract"
    const val CACHE_LETTUCE = ":$ROOT_PROJECT_NAME-cache-lettuce"
    const val CACHE_MAP = ":$ROOT_PROJECT_NAME-cache-map"
    const val CACHE_REDIS = ":$ROOT_PROJECT_NAME-cache-redis"

    const val CLOUD_COMMUNICATION_DROMARA_SMS = ":$ROOT_PROJECT_NAME-cloud-communication-dromara-sms"
    const val CLOUD_COMMUNICATION_JAKARTA = ":$ROOT_PROJECT_NAME-cloud-communication-jakarta"
    const val CLOUD_NATIVE_DOCKER = ":$ROOT_PROJECT_NAME-cloud-native-docker"
    const val CLOUD_NATIVE_KUBERNETES = ":$ROOT_PROJECT_NAME-cloud-native-kubernetes"

    const val CONCURRENT_ACTOR = ":$ROOT_PROJECT_NAME-concurrent-actor"
    const val CONCURRENT_REDIS = ":$ROOT_PROJECT_NAME-concurrent-redis"

    const val CONTRACT_COMPONENT_REDIS = ":$ROOT_PROJECT_NAME-contract-component-redis"
    const val CONTRACT_COMPONENT_OSS = ":$ROOT_PROJECT_NAME-contract-component-oss"
    const val CONTRACT_CONSTANT = ":$ROOT_PROJECT_NAME-contract-constant"
    const val CONTRACT_MODEL = ":$ROOT_PROJECT_NAME-contract-model"

    const val DOC_KNIFE4J_CONTRACT = ":$ROOT_PROJECT_NAME-doc-knife4j-contract"
    const val DOC_KNIFE4J_SPRING_GATEWAY = ":$ROOT_PROJECT_NAME-doc-knife4j-spring-gateway"
    const val DOC_KNIFE4J_SPRING_WEBMVC = ":$ROOT_PROJECT_NAME-doc-knife4j-spring-webmvc"
    const val DOC_KNIFE4J_SPRING_WEBFLUX = ":$ROOT_PROJECT_NAME-doc-knife4j-spring-webflux"

    const val GATEWAY_SPRING = ":$ROOT_PROJECT_NAME-gateway-spring"

    const val JDBC_CASSANDRA = ":$ROOT_PROJECT_NAME-jdbc-cassandra"
    const val JDBC_DA_MENG = ":$ROOT_PROJECT_NAME-jdbc-da-meng"
    const val JDBC_ELASTICSEARCH = ":$ROOT_PROJECT_NAME-jdbc-elasticsearch"
    const val JDBC_HSQLDB = ":$ROOT_PROJECT_NAME-jdbc-hsqldb"
    const val JDBC_MARIADB = ":$ROOT_PROJECT_NAME-jdbc-mariadb"
    const val JDBC_MYSQL = ":$ROOT_PROJECT_NAME-jdbc-mysql"
    const val JDBC_POSTGIS = ":$ROOT_PROJECT_NAME-jdbc-postgis"
    const val JDBC_POSTGRESQL = ":$ROOT_PROJECT_NAME-jdbc-postgresql"
    const val JDBC_SQL_SERVER = ":$ROOT_PROJECT_NAME-jdbc-sql-server"
    const val JDBC_TDENGINE = ":$ROOT_PROJECT_NAME-jdbc-tdengine"

    const val MESSAGE_ENGINE_CONTRACT = ":$ROOT_PROJECT_NAME-message-engine-contract"
    const val MESSAGE_ENGINE_CLIENT_ALL = ":$ROOT_PROJECT_NAME-message-engine-client-all"
    const val MESSAGE_ENGINE_CLIENT_CONTRACT = ":$ROOT_PROJECT_NAME-message-engine-client-contract"
    const val MESSAGE_ENGINE_CLIENT_KAFKA = ":$ROOT_PROJECT_NAME-message-engine-client-kafka"
    const val MESSAGE_ENGINE_CLIENT_MQTT_CONTRACT = ":$ROOT_PROJECT_NAME-message-engine-client-mqtt-contract"
    const val MESSAGE_ENGINE_CLIENT_MQTT_V3 = ":$ROOT_PROJECT_NAME-message-engine-client-mqtt-v3"
    const val MESSAGE_ENGINE_CLIENT_MQTT_V5 = ":$ROOT_PROJECT_NAME-message-engine-client-mqtt-v5"
    const val MESSAGE_ENGINE_CLIENT_RABBITMQ = ":$ROOT_PROJECT_NAME-message-engine-client-rabbitmq"
    const val MESSAGE_ENGINE_CLIENT_REDIS_STREAM = ":$ROOT_PROJECT_NAME-message-engine-client-redis-stream"
    const val MESSAGE_ENGINE_CLIENT_ROCKETMQ = ":$ROOT_PROJECT_NAME-message-engine-client-rocketmq"
    const val MESSAGE_ENGINE_SERVER_CONTRACT = ":$ROOT_PROJECT_NAME-message-engine-server-contract"
    const val MESSAGE_ENGINE_SERVER_MQTT = ":$ROOT_PROJECT_NAME-message-engine-server-mqtt"

    const val METRIC_DROP_WIZARD = ":$ROOT_PROJECT_NAME-metric-drop-wizard"
    const val METRIC_MICROMETER_PROMETHEUS = ":$ROOT_PROJECT_NAME-metric-micrometer-prometheus"
    const val METRIC_SPRING = ":$ROOT_PROJECT_NAME-metric-spring"
    const val METRIC_SYSTEM = ":$ROOT_PROJECT_NAME-metric-system"

    const val ORM_CONTRACT = ":$ROOT_PROJECT_NAME-orm-contract"
    const val ORM_CONTRACT_MYBATIS_BASE = ":$ROOT_PROJECT_NAME-orm-contract-mybatis-base"
    const val ORM_CONTRACT_MYBATIS_BASE_POSTGIS = ":$ROOT_PROJECT_NAME-orm-contract-mybatis-base-postgis"
    const val ORM_CONTRACT_MYBATIS_BASE_POSTGRESQL = ":$ROOT_PROJECT_NAME-orm-contract-mybatis-base-postgresql"
    const val ORM_CONTRACT_MYBATIS_FLEX = ":$ROOT_PROJECT_NAME-orm-contract-mybatis-flex"
    const val ORM_MYBATIS_FLEX_BASE = ":$ROOT_PROJECT_NAME-orm-mybatis-flex-base"
    const val ORM_MYBATIS_FLEX_POSTGIS = ":$ROOT_PROJECT_NAME-orm-mybatis-flex-postgis"
    const val ORM_MYBATIS_FLEX_POSTGRESQL = ":$ROOT_PROJECT_NAME-orm-mybatis-flex-postgresql"
    const val ORM_MYBATIS_FLEX_TDENGINE = ":$ROOT_PROJECT_NAME-orm-mybatis-flex-tdengine"
    const val ORM_MYBATIS_PLUS = ":$ROOT_PROJECT_NAME-orm-mybatis-plus"
    const val ORM_SPRING_JDBC = ":$ROOT_PROJECT_NAME-orm-spring-jdbc"
    const val ORM_SPRING_JPA = ":$ROOT_PROJECT_NAME-orm-spring-jpa"

    const val OSS_API = ":$ROOT_PROJECT_NAME-oss-api"
    const val OSS_CONTRACT = ":$ROOT_PROJECT_NAME-oss-contract"
    const val OSS_LOCAL = ":$ROOT_PROJECT_NAME-oss-local"
    const val OSS_MINIO = ":$ROOT_PROJECT_NAME-oss-minio"

    const val PLUGGABLE_ANNOTATION_API_LOMBOK = ":$ROOT_PROJECT_NAME-pluggable-annotation-api-lombok"
    const val PLUGGABLE_ANNOTATION_API_MICA_AUTO = ":$ROOT_PROJECT_NAME-pluggable-annotation-api-mica-auto"
    const val PLUGGABLE_ANNOTATION_API_PROCESSOR_JMH = ":$ROOT_PROJECT_NAME-pluggable-annotation-api-processor-jmh"
    const val PLUGGABLE_ANNOTATION_API_PROCESSOR_LOMBOK_MAPSTRUCT_BINDING = ":$ROOT_PROJECT_NAME-pluggable-annotation-api-processor-lombok-mapstruct-binding"
    const val PLUGGABLE_ANNOTATION_API_PROCESSOR_MAPSTRUCT_PLUS = ":$ROOT_PROJECT_NAME-pluggable-annotation-api-processor-mapstruct-plus"
    const val PLUGGABLE_ANNOTATION_API_PROCESSOR_MAPSTRUCT_PROTOBUF = ":$ROOT_PROJECT_NAME-pluggable-annotation-api-processor-mapstruct-protobuf"
    const val PLUGGABLE_ANNOTATION_API_PROCESSOR_MYBATIS_FLEX = ":$ROOT_PROJECT_NAME-pluggable-annotation-api-processor-mybatis-flex"
    const val PLUGGABLE_ANNOTATION_API_PROCESSOR_SPRING = ":$ROOT_PROJECT_NAME-pluggable-annotation-api-processor-spring"

    const val POOL_APACHE = ":$ROOT_PROJECT_NAME-pool-apache"
    const val POOL_DATABASE_HIKARICP = ":$ROOT_PROJECT_NAME-pool-database-hikaricp"

    const val PROTOCOL_JAVAX_SIP = ":$ROOT_PROJECT_NAME-protocol-javax-sip"

    const val REGISTRATION_NACOS = ":$ROOT_PROJECT_NAME-registration-nacos"
    const val REGISTRATION_ZOOKEEPER = ":$ROOT_PROJECT_NAME-registration-zookeeper"

    const val SECURITY_CONTRACT = ":$ROOT_PROJECT_NAME-security-contract"
    const val SECURITY_SPRING = ":$ROOT_PROJECT_NAME-security-spring"
    const val SECURITY_SA_TOKEN = ":$ROOT_PROJECT_NAME-security-sa-token"

    const val STUDIO_LOW_CODE = ":$ROOT_PROJECT_NAME-studio-low-code"

    const val TEST_CONTAINER = ":$ROOT_PROJECT_NAME-test-container"
    const val TEST_JMH = ":$ROOT_PROJECT_NAME-test-jmh"
    const val TEST_JUNIT = ":$ROOT_PROJECT_NAME-test-junit"
    const val TEST_MOCKITO = ":$ROOT_PROJECT_NAME-test-mockito"
    const val TEST_SPRING_BOOT = ":$ROOT_PROJECT_NAME-test-spring-boot"
    const val TEST_SPRING_INTEGRATION = ":$ROOT_PROJECT_NAME-test-spring-integration"

    const val TOOL_CONTENT_ANALYSIS = ":$ROOT_PROJECT_NAME-tool-content-analysis"
    const val TOOL_CONVERT_API = ":$ROOT_PROJECT_NAME-tool-convert-api"
    const val TOOL_CONVERT_JACKSON = ":$ROOT_PROJECT_NAME-tool-convert-jackson"
    const val TOOL_CONVERT_JACKSON_GEOMETRY = ":$ROOT_PROJECT_NAME-tool-convert-jackson-geometry"
    const val TOOL_CONVERT_MAPSTRUCT_PLUS = ":$ROOT_PROJECT_NAME-tool-convert-mapstruct-plus"
    const val TOOL_CONVERT_MAPSTRUCT_PROTOBUF = ":$ROOT_PROJECT_NAME-tool-convert-mapstruct-protobuf"
    const val TOOL_CONVERT_PROTOBUF = ":$ROOT_PROJECT_NAME-tool-convert-protobuf"
    const val TOOL_CONVERT_SPRING = ":$ROOT_PROJECT_NAME-tool-convert-spring"
    const val TOOL_ENUMS = ":$ROOT_PROJECT_NAME-tool-enums"
    const val TOOL_EXCEL = ":$ROOT_PROJECT_NAME-tool-excel"
    const val TOOL_GEOMETRY = ":$ROOT_PROJECT_NAME-tool-geometry"
    const val TOOL_ID_SNOWFLAKE = ":$ROOT_PROJECT_NAME-tool-id-snowflake"
    const val TOOL_ID_UUID = ":$ROOT_PROJECT_NAME-tool-id-uuid"
    const val TOOL_JDK = ":$ROOT_PROJECT_NAME-tool-jdk"
    const val TOOL_JNA = ":$ROOT_PROJECT_NAME-tool-jna"
    const val TOOL_JOB_QUARTZ = ":$ROOT_PROJECT_NAME-tool-job-quartz"
    const val TOOL_LANG = ":$ROOT_PROJECT_NAME-tool-lang"
    const val TOOL_LOG = ":$ROOT_PROJECT_NAME-tool-log"
    const val TOOL_RATE_LIMITING = ":$ROOT_PROJECT_NAME-tool-rate-limiting"
    const val TOOL_SERIALIZATION_FASTJSON = ":$ROOT_PROJECT_NAME-tool-serialization-fastjson"
    const val TOOL_SERIALIZATION_FASTJSON2 = ":$ROOT_PROJECT_NAME-tool-serialization-fastjson2"
    const val TOOL_SERIALIZATION_FST = ":$ROOT_PROJECT_NAME-tool-serialization-fst"
    const val TOOL_SERIALIZATION_JACKSON = ":$ROOT_PROJECT_NAME-tool-serialization-jackson"
    const val TOOL_SERIALIZATION_PROTOBUF_GOOGLE = ":$ROOT_PROJECT_NAME-tool-serialization-protobuf-google"
    const val TOOL_SERIALIZATION_PROTOBUF_SQUAREUP = ":$ROOT_PROJECT_NAME-tool-serialization-protobuf-squareup"
    const val TOOL_SPRING_CONTRACT = ":$ROOT_PROJECT_NAME-tool-spring-contract"
    const val TOOL_SPRING_WEBFLUX = ":$ROOT_PROJECT_NAME-tool-spring-webflux"
    const val TOOL_SPRING_WEBMVC = ":$ROOT_PROJECT_NAME-tool-spring-webmvc"
    const val TOOL_TEMPLATE_ENGINE = ":$ROOT_PROJECT_NAME-tool-template-engine"
    const val TOOL_THREAD_POOL_CONTRACT = ":$ROOT_PROJECT_NAME-tool-thread-pool-contract"
    const val TOOL_THREAD_POOL_CONFIG_NACOS = ":$ROOT_PROJECT_NAME-tool-thread-pool-config-nacos"
    const val TOOL_THREAD_POOL_INTEGRATION_GRPC = ":$ROOT_PROJECT_NAME-tool-thread-pool-integration-grpc"
    const val TOOL_THREAD_POOL_INTEGRATION_OKHTTP3 = ":$ROOT_PROJECT_NAME-tool-thread-pool-integration-okhttp3"
    const val TOOL_THREAD_POOL_INTEGRATION_TOMCAT = ":$ROOT_PROJECT_NAME-tool-thread-pool-integration-tomcat"
    const val TOOL_VALIDATION_HIBERNATE = ":$ROOT_PROJECT_NAME-tool-validation-hibernate"
    const val TOOL_VALIDATION_JAKARTA = ":$ROOT_PROJECT_NAME-tool-validation-jakarta"
    const val TOOL_VALIDATION_JSON_SCHEMA = ":$ROOT_PROJECT_NAME-tool-validation-json-schema"
    const val TOOL_VALIDATION_SPRING = ":$ROOT_PROJECT_NAME-tool-validation-spring"
    const val TOOL_XML = ":$ROOT_PROJECT_NAME-tool-xml"

    const val TRANSACTION_SPRING = ":$ROOT_PROJECT_NAME-transaction-spring"

    const val WEB_GRPC_CLIENT = ":$ROOT_PROJECT_NAME-web-grpc-client"
    const val WEB_GRPC_CONTRACT = ":$ROOT_PROJECT_NAME-web-grpc-contract"
    const val WEB_GRPC_SERVER = ":$ROOT_PROJECT_NAME-web-grpc-server"
    const val WEB_HTTP_OKHTTPS = ":$ROOT_PROJECT_NAME-web-http-okhttps"
    const val WEB_OPEN_FEIGN = ":$ROOT_PROJECT_NAME-web-openfeign"
    const val WEB_REACTOR = ":$ROOT_PROJECT_NAME-web-reactor"
    const val WEB_WEBSOCKET = ":$ROOT_PROJECT_NAME-web-websocket"

}